version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  nestjs-app:
    build: .
    ports:
      - "3333:3333" 
    environment:
      NODE_ENV: development   
      JWT_SECRET: YOUR_SECRET_KEY_HERE
      JWT_TOKEN_AUDIENCE: localhost:3000
      JWT_TOKEN_ISSUER: localhost:3000
      JWT_ACCESS_TOKEN_TTL: 3600

    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
